#!/bin/sh
#
# makefnt <name>
#
#  output the font to ../fonts directory
#

SIZES="10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48"
#SIZES="50 52 54 56 58 60 62 64 66 68 70"
EFNTTOOL=../../../../bin/efnttool

for sz in $SIZES; do
    $EFNTTOOL -o ../fonts/$1$sz.efnt -xres 75 -yres 75 -ft $1.ttf $sz
done
